version: '3'

services: 
    nginx_lb:
        build: ngnix
        ports: 
            - 80:80

    node1:
        build: .
        environment:
            - NODE_ENV=production
            - APP_ID=1
            - PORT=5000
    node2:
        build: .
        environment:
            - NODE_ENV=production
            - APP_ID=2
            - PORT=5000
    node3:
        build: .
        environment:
            - NODE_ENV=production
            - APP_ID=3
            - PORT=5000
