version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
   
    networks:
      - app-network
  app2:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '13000:13000'
    environment:
      - NODE_ENV=production
    
    networks:
      - app-network

  load-balancer:
    image: nginx
    ports:
      - '80:80'
    volumes:
      - .nginx-c.conf:/etc/nginx/nginx.conf:ro
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
