name: Node.js CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and test
        run: docker-compose build && docker-compose run --rm node1 && docker-compose run --rm node2 && docker-compose run --rm node3
